bin/convert_from_pretalx.py: Support empty biographies
This is required for the current schedule:
```
Traceback (most recent call last):
  File "bin/convert_from_pretalx.py", line 62, in <module>
    talks = list(gen_talks())
  File "bin/convert_from_pretalx.py", line 35, in gen_talks
    names, bios = merge_persons(talk['persons'])
  File "bin/convert_from_pretalx.py", line 19, in merge_persons
    bios = "\n\n".join(p['biography'] for p in persons)
TypeError: sequence item 1: expected str instance, NoneType found
```

We should probably improve the biography merging a bit but this should
be good enough for now.